import fs from "node:fs";
import path from "node:path";

export const VAULT_NAME = ".instinctgate";

export function resolveVault(cwd = process.cwd(), explicit?: string): string {
  if (explicit) return path.resolve(explicit);
  return path.join(cwd, VAULT_NAME);
}

export function ensureVault(vaultRoot: string): void {
  const dirs = ["instincts", "skills", "scorecards"];
  for (const d of dirs) {
    fs.mkdirSync(path.join(vaultRoot, d), { recursive: true });
  }
  const readme = path.join(vaultRoot, "README.md");
  if (!fs.existsSync(readme)) {
    fs.writeFileSync(
      readme,
      `# InstinctGate vault

- \`instincts/\` — pattern candidates with confidence
- \`skills/\` — promoted SKILL.md stubs
- \`scorecards/\` — per-run verification scores

Generated by \`instinctgate\`. Safe to commit.
`,
      "utf8"
    );
  }
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60) || "untitled";
}

export interface Frontmatter {
  [key: string]: string | number | boolean;
}

export function parseFrontmatter(raw: string): { data: Frontmatter; body: string } {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data: Frontmatter = {};
  for (const line of m[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let val: string | number | boolean = line.slice(idx + 1).trim();
    if (val === "true") val = true;
    else if (val === "false") val = false;
    else if (/^-?\d+(\.\d+)?$/.test(val)) val = Number(val);
    else if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    data[key] = val;
  }
  return { data, body: m[2].replace(/^\r?\n/, "") };
}

export function stringifyFrontmatter(data: Frontmatter, body: string): string {
  const lines = Object.entries(data).map(([k, v]) => {
    if (typeof v === "string" && (v.includes(":") || v.includes("#"))) {
      return `${k}: "${v.replace(/"/g, '\\"')}"`;
    }
    return `${k}: ${v}`;
  });
  return `---\n${lines.join("\n")}\n---\n\n${body.trim()}\n`;
}
